Numpy

In [1]:
import numpy as np

In [5]:
#Converting python sequences to NUmpy Arrays
array1D = np.array([1,2,3,4,5,6,7,8,9])
array1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
array2D = np.array(
    [[1,2], [3,4]]
)
array2D

array([[1, 2],
       [3, 4]])

In [9]:
arrayUni = np.array(
        [ 
            [[1,2],[3,4]],
            [[5,6], [7,8]]  
        ]
    )
arrayUni

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
#When you use numpy.array to define a new array, you should consider the dtype of the elements in the array,
#which can be specified explicitly
array8b = np.array([127, 128, 129] , dtype = np.int8)
array8b

C:\Users\Tomas\AppData\Local\Temp\ipykernel_14600\1184940092.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  array8b = np.array([127, 128, 129] , dtype = np.int8)
C:\Users\Tomas\AppData\Local\Temp\ipykernel_14600\1184940092.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  array8b = np.array([127, 128, 129] , dtype = np.int8)


array([ 127, -128, -127], dtype=int8)

In [15]:
a = np.array([2, 3, 4], dtype=np.uint32)
b = np.array([5, 6, 7], dtype=np.uint32)
c_unsigned32 = a - b
print('unsigned c:', c_unsigned32, c_unsigned32.dtype)
c_signed32 = a - b.astype(np.int32)
print('signed c:', c_signed32, c_signed32.dtype)

unsigned c: [4294967293 4294967293 4294967293] uint32
signed c: [-3 -3 -3] int64


#Este codigo se encarga de hacer algo
*Hola

In [23]:
np.arange(10)
np.arange(2, 10, dtype=float)
np.arange(2,3,0.1)
np.linspace(1., 4. ,10)
np.vander((1, 2, 3, 4),4) #Vander imagen
np.zeros((2, 3))
np.zeros((2, 3, 2))
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

#Acceder

In [26]:
a = np.array([1,2,3,4])
b = a[:2] #Cuidado con el acceso a la memoria
b = a[:2].copy()
b += 1
print('a ', a, 'b', b)

a  [1 2 3 4] b [2 3]


In [27]:
for fila in range(len(a)):
    print(a[fila],' ',)

1  
2  
3  
4  


In [29]:
x = np.arange(15)
print('x ', x)
print('x[2]', x[2])
print('x[-3]', x[-3])
z = x.shape = (3, 5)
print('z ', z)
print('x[0, 1]', x[0,1])

x  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
x[2] 2
x[-3] 12
z  (3, 5)
x[0, 1] 1


In [30]:
print("Imprimiendo valores")
for fila in range(z[0]):
    for columna in range(z[1]):
        print(x[fila, columna], end = " ")
    print()

Imprimiendo valores
0 1 2 3 4 
5 6 7 8 9 
10 11 12 13 14 


In [31]:
np.loadtxt('simple.csv', delimiter = ',', skiprows = 1)
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])