Numpy

In [4]:
import numpy as np


In [8]:
#Converting python sequences to NUmpy Arrays
array1D = np.array([1,2,3,4,5,6,7,8,9])
array1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
array2D = np.array([[1,2], [3,4]])
array2D

array([[1, 2],
       [3, 4]])

In [14]:
arrayUni = np.array([ [[1,2],[3,4]], [[5,6], [7,8]]  ])
arrayUni

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
#When you use numpy.array to define a new array, you should consider the dtype of the elements in the array,
#which can be specified explicitly
array8b = np.array([127, 128, 129] , dtype = np.int8)
array8b

C:\Users\Tomas\AppData\Local\Temp\ipykernel_19936\3416476132.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  array8b = np.array([127, 128, 129] , dtype = np.int8)
C:\Users\Tomas\AppData\Local\Temp\ipykernel_19936\3416476132.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  array8b = np.array([127, 128, 129] , dtype = np.int8)


array([ 127, -128, -127], dtype=int8)

In [19]:
a = np.array([2, 3, 4], dtype=np.uint32)
b = np.array([5, 6, 7], dtype=np.uint32)
c_unsigned32 = a - b
print('unsigned c:', c_unsigned32, c_unsigned32.dtype)
c_signed32 = a - b.astype(np.int32)
print('signed c:', c_signed32, c_signed32.dtype)